metro.config.js

This PR will enable Class Variance Authority to work with metro bundler for expo web.

fix: mjs, cjs module resolution to account for es6 node libraries

---

app/(main)/(tabs)/_layout.tsx

Resolves the following metro web error:
> Warning: Received `true` for a non-boolean attribute `focused`.
> If you want to write it to the DOM, pass a string instead: focused="true" or focused={value.toString()}.

Lucide Icons only need color, size and strokeWidth props

---

README.md

Case:
The url to the website "ui.shadcn.com" is not working correctly. I share a screenshot.
Solution:
Add https in front of the link so that it opens as a website outside of Github.

Add https prefix to ui.shadcn.com url

---

components/ui/button.tsx

The button size variants had duplicate padding classNames which were giving eslint errors

chore: remove duplicate classNames for button

---

components/universal-ui/button.tsx

Button component receives onPressOut prop but there is a typo so onPressOut prop never gets called. onPressIn gets called instead.
Fix the typo.
In `app/(main)/button/button-universal.tsx`, add the following prop and tap on the button to confirm both gets called on this branch.
```
<Button
onPressIn={() => {
console.log('onPressIn');
}}
onPressOut={() => {
console.log('onPressOut');
}}
>
```

fix(universal): onPressOut event handler in Button component

---

.prettierrc.json
components/ui/checkbox.tsx

This updates the Checkbox  to do 3 small things:
1. use a Forward Ref component on a View (not an SVG)
2. the 'hook' approach' via `useSharedValue` and `withTiming` hooks
3. animate `opacity` via the `useSharedValue`
This resolves https://github.com/mrzachnugent/react-native-reusables/issues/30
I also added a prettierrc.json at the root of the project that should match the existing code style (I noticed you favored single quotes over double, so this enforces that)

Fix: Issue 30 : fixes the checkbox animation on web export

---

.prettierrc.json
components/ui/toast.tsx
lib/useIsomorphicLayoutEffect.tsx

1. adds a line of code to prevent accessing function on server that causes verbose logging
2. adds a prettierrc.json that matches the existing code style

Fix: Issue 32:  Verbose logging about useLayoutEffect on server render with web-export with toast component

---

.prettierrc.json
components/ui/progress.tsx

converts to 
```tsx
<Animated.View {...props} style={[stylez, style]}>
<View className={cn('h-4 bg-foreground', className)}></View>
</Animated.View>
```
because `<View />` accepts the `className` property. Functionality is otherwise identical

Fix Issue 36: Fix progress so it renders on the web as well as mobile devices

---

.prettierrc.json
components/ui/radio-group.tsx

changes `[borderWidth:1.5] ` to `native:[borderWidth:1.5] web:border`
| Before | After  |
|--------|--------|
| ![image](https://github.com/mrzachnugent/react-native-reusables/assets/954596/75b8b196-b19a-475e-b9ab-039f0cce9bea)| ![image](https://github.com/mrzachnugent/react-native-reusables/assets/954596/c727076c-cc69-4c2b-b9f7-b9eb7920109f)|

Fix issue 38: Radio: adds borders to the radio buttons on web same as mobile

---

package-lock.json
package.json

- removes the `^` from nativewind, locking it at 4.0.13
- regenerated package-lock.json

lock nativewind at 4.0.13 and regen package-lock.json

---

packages/primitives/switch/src/switch.tsx
packages/primitives/switch/src/switch.web.tsx
packages/reusables/src/components/ui/switch.tsx

Fixes `displayName` for `Thumb` in `Switch` primitives (https://github.com/mrzachnugent/react-native-reusables/issues/109)
Additionally, adds a const assertion to `components/ui/switch.tsx` so the typecheck passes for line 61 of that same file:
```
const RGB_COLORS = {
light: {
primary: 'rgb(24, 24, 27)',
input: 'rgb(228, 228, 231)',
},
dark: {
primary: 'rgb(250, 250, 250)',
input: 'rgb(39, 39, 42)',
},
} as const;
```

Switch fixes

---

packages/primitives/popover/src/popover.tsx

This fixes one case but now running into another error:
```
ERROR  ReanimatedError: Cannot convert undefined value to object, js engine: reanimated
```
```
ERROR  Invariant Violation: Rotate transform must be expressed in degrees (deg) or radians (rad): {"rotate":"initial"}
This error is located at:
in RCTView (created by CssInterop.View)
in CssInterop.View (created by AnimatedComponent(View))
in AnimatedComponent(View)
in Unknown (created by CSSInteropAnimationWrapper(View))
in CSSInteropAnimationWrapper(View) (created by CssInterop.View)
in CssInterop.View (created by ContentNativePopover)
in ContentNativePopover (created by ContentNativePopover)
in RCTView (created by CssInterop.View)
in CssInterop.View (created by AnimatedComponent(View))
in AnimatedComponent(View)
in Unknown (created …
```

Popover not working on iOS

---

apps/starter-base/package.json

After I try to run starter app I got the next error
```
Metro error: Unable to resolve module /mnt/c/users/user/documents/github/react-native-reusables/apps/starter-base/node_modules/.cache/nativewind/global.css from /mnt/c/users/user/documents/github/react-native-reusables/apps/starter-base/global.css:
```
- apps/starter-base
I think the postinstall script which exist in `apps\showcase\package.json` is missing
```json
"scripts": {
"dev": "expo start -c --ios",
"dev:web": "expo start -c --web",
"dev:android": "expo start -c --android",
"android": "expo start -c --android",
"ios": "expo start -c --ios",
"web": "expo start -c --web",
"clean": "rm -rf .expo node_modules",
"postinstall": "npx tailwindcss -i ./global.css -o ./node_modules/.cache/nativewind/global.css" …
```

Missing ./node_modules/.cache/nativewind/global.css

---

apps/docs/src/content/docs/components/separator.mdx
packages/reusables/src/components/ui/switch.tsx

Typo Fix:
The title has a typo as "Separtor", https://rnr-docs.vercel.app/components/separator/
UI Bug fix:
The Web version of the Switch component has a condition as follows
```
const SwitchWeb = React.forwardRef<
React.ElementRef<typeof SwitchPrimitives.Root>,
React.ComponentPropsWithoutRef<typeof SwitchPrimitives.Root>
>(({ className, ...props }, ref) => (
<SwitchPrimitives.Root
className={cn(
"peer flex-row h-6 w-11 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed",
props.checked ? "bg-primary" : "bg-input",
props.disabled && "opacity-50",  // THIS LINE
className
)}
{...props} …
```

fix(ui): switch component ui bug & fix(docs): typo

---

packages/reusables/src/components/ui/dialog.tsx

Prevent conflicting with other portal components such as tooltip and popover.
I am unsure why this was set. Nothing seems different when I remove it.
ETA: other portal components define the same thing.

fix(dialog): remove z-50

---

apps/starter-base/app/_layout.tsx

When the app is first opened, safe area zones on Android are not updated to match the theme.
apps/starter-base
After:

fix: unstable android navigation bar theme

---

README.md

Updated link to NativeWind documentation as the previous link returned a 'Page Not Found' error.

Fix broken link to NativeWind documentation

---

apps/cli/package.json
apps/cli/scripts/generate-source-files.ts
apps/cli/src/commands/init.ts
apps/cli/src/index.ts
apps/cli/src/items/templates.ts
apps/docs/package.json
apps/docs/src/content/docs/getting-started/initial-setup.mdx
pnpm-lock.yaml

Add new CLI command 'init' to automate project setup. The command installs required dependencies.
Key features:
- Installs essential dependencies (nativewind, async-storage, etc.)
- Configures path aliases
- Copies utility files
- Supports overwriting existing files with confirmation prompt
- [apps/cli] - Added new init command
- [apps/docs] - Updated documentation for initial setup
Usage:
```bash
npx @react-native-reusables/cli@latest init [options]

Add init command for project setup

---

apps/docs/src/content/docs/components/label.mdx

Saw this when was browsing the docs and thought I would fix it. The L in label should be capitalised in the import.
N/A
N/A

doc: Fix Label components usage code

---

apps/cli/src/services/commands/add.ts
apps/cli/src/services/package-manager.ts

This fixes a bug where the `@react-native-reusables/cli` produced invalid commands for yarn berry projects.
For example:
```sh
yarn dlx @react-native-reusables/cli add aspect-ratio
Unknown Syntax Error: Unsupported option name ("--yes").
ERROR (#16): Failed to run command: yarn --yes shadcn@latest add https://reactnativereusables.com/r/new-york/aspect-ratio.json
```
The above command should have been:
```sh
yarn dlx shadcn@latest add https://reactnativereusables.com/r/new-york/aspect-ratio.json
```
I have also opened a PR against shadcn to fix a similar bug with their expo install handling, which always uses npx rather than the appropriate package manager to run `expo install`: https://github.com/shadcn-ui/ui/pull/8208. Until this merges, expo projects will still have a somewhat broken …

Fix yarn berry commands

---

packages/registry/src/new-york/components/ui/input.tsx

PlaceholderClassName was deconstructed from the Input props and was not passed into the TextInput from React Native. 
This was a one line change.
Fixes issue #

fix(input): added placeholderClassName to TextInput props

---

apps/docs/components/command-tabs.tsx

This pull request updates the `CommandTabs` component to support an additional package manager variant, improving compatibility with different developer environments.
Package manager support:
* Added `yarn@berry` to the `MANAGERS` array in `command-tabs.tsx` to support Yarn Berry (v2+) commands.
* Updated the `COMMAND` mapping to include the correct command structure for `yarn@berry`. introduced by this pull request. 
Fixes issue [](https://github.com/founded-labs/react-native-reusables/issues/435)

feat(docs): add yarn@berry command option
